config/routes.rb
Clipping::Application.routes.draw do
  resources :webpages

end

app/models/webpage.rb
class Webpage < ActiveRecord::Base
  attr_accessible :description, :title, :url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/webpages_controller.rb
# coding: utf-8
class WebpagesController < ApplicationController
  def index
    @webpages = Webpage.all
    @webpage = Webpage.new
  end

  def show id
    @webpage = Webpage.find id
  end

  def new
    @webpage = Webpage.new
  end

  def edit id
    @webpage = Webpage.find id
  end

  def create webpage
    @webpage = Webpage.new webpage

    if @webpage.save
      redirect_to @webpage, notice: 'Webpage was successfully created.'
    else
      render action: "new"
    end
  end

  def update id, webpage
    @webpage = Webpage.find id

    if @webpage.update_attributes webpage
      redirect_to @webpage, notice: 'Webpage was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy id
    @webpage = Webpage.find id
    @webpage.destroy
    redirect_to webpages_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/webpages_helper.rb
module WebpagesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Clipping
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    #header
      .body
        %h1 Clipping
    #content
      .body= yield
    #footer
      .body
        hogehoge

app/views/webpages/_form.html.haml
= form_for @webpage do |f|
  - if @webpage.errors.any?
    #error_explanation
      %h2= "#{pluralize(@webpage.errors.count, "error")} prohibited this webpage from being saved:"
      %ul
        - @webpage.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :url
    = f.text_field :url
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/webpages/edit.html.haml
%h1 Editing webpage

= render 'form'

= link_to 'Show', @webpage
\|
= link_to 'Back', webpages_path

app/views/webpages/index.html.haml
%h2 Listing webpages

= form_for @webpage do |f|
  %dl
    %dt= f.label :title
    %dd= f.text_field :title
    %dt= f.label :url
    %dd= f.url_field :url
    %dt= f.label :description
    %dd= f.text_area :description

  %nav
    %p= f.submit 'Register'

- @webpages.each do |webpage|
  %article
    %h3= webpage.title
    %p= link_to webpage.url, webpage.url
    = simple_format webpage.description

    %aside
      = link_to 'Show', webpage
      |
      = link_to 'Edit', edit_webpage_path(webpage)
      |
      = link_to 'Destroy', webpage, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Webpage', new_webpage_path

app/views/webpages/new.html.haml
%h1 New webpage

= render 'form'

= link_to 'Back', webpages_path

app/views/webpages/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @webpage.title
%p
  %b Url:
  = @webpage.url
%p
  %b Description:
  = @webpage.description

= link_to 'Edit', edit_webpage_path(@webpage)
\|
= link_to 'Back', webpages_path